-- setup table for client_profiles
create table client_profiles (
    id uuid primary key default uuid_generate_v4(),
    first_name varchar (255),
    last_name varchar (255),
    email varchar (255) unique,
    service varchar (255),
    reason_for_massage varchar (1000),
    other_hcp varchar (255),
    doctor_name varchar (255),
    doctor_address varchar (1000),
    cardio_none boolean,
    high_blood_pressure boolean,
    low_blood_pressure boolean,
    heart_attack boolean,
    vericose_veins boolean,
    stroke boolean,
    pacemaker boolean,
    heart_disease boolean,
    resp_none boolean,
    chronic_cough boolean,
    bronchitis boolean,
    asthma boolean,
    emphysema boolean,
    skin_conditions varchar (1000),
    infectious_conditions varchar (1000),
    diabetes boolean,
    epilepsy boolean,
    cancer boolean,
    arthritis boolean,
    chronic_headaches boolean,
    migraine_headaches boolean,
    vision_loss boolean,
    hearing_loss boolean,
    osteoporosis boolean,
    haemophilia boolean,
    medical_conditions varchar (1000),
    allergies varchar (500),
    medications varchar (500),
    glutes boolean,
    inner_thighs boolean,
    abdomen boolean,
    chest_wall boolean,
    all_areas boolean,
    sensitive_areas varchar(1000),
    privacy_policy boolean,
    phone varchar (255),
    pregnant varchar(255),
    massage_history varchar (255),
    occupation varchar (255),
    loss_of_feeling boolean,
    date_of_birth varchar(255),
    password varchar(255),
    address varchar(1000),
    injuries varchar(1000),
    general_health varchar(1000),
    pronouns varchar(255),
    surgeries varchar(1000),
    date_updated varchar(255),
    gynecological varchar(1000)
);

create table appointments (
    appointment_id uuid primary key default uuid_generate_v4(),
    client_id uuid not null references client_profiles(id),
    appointment_date date,
    consent_for_treatment boolean,
    duration smallint,
    price smallint,
    treatment_purpose varchar(1000),
    findings varchar(2000),
    treatment varchar(5000),
    immediate_results varchar(2000),
    remex varchar(5000),
    treatment_plan varchar(5000),
    time varchar(255),
    credit boolean,
    debit boolean,
    cash_etransfer boolean,
    send_receipt boolean,
    consent_glutes boolean,
    consent_innerthighs boolean,
    consent_abdomen boolean,
    consent_chest boolean,
    sensitive_areas varchar(1000),
    notes varchar(1000)
);

create table rmtprofiles (
    id uuid primary key default uuid_generate_v4(),
    first_name varchar(255) not null,
    last_name varchar(255) not null,
    email varchar (255) not null,
    password varchar (1000) not null
);
